//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalAPI.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONACIONE
    {
        public int id { get; set; }
        public Nullable<int> refugio_ID { get; set; }
        public Nullable<int> donante_ID { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
        public virtual REFUGIO REFUGIO { get; set; }
    }
}
