//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalAPI.ModeloDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES
    {
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public string nombre { get; set; }
        public string extension { get; set; }
        public string url { get; set; }
        public byte[] imagen { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
